### ISSUE TITLE
Add support for static resource bundle deployment

### ISSUE THREAD

**Issue by iDev0urer** [kevinohara80/grunt-ant-sfdc#36]
It would be nice if there was an option in the deploy settings for resource bundles as well. It wouldn't be too difficult to then zip the files within the folder and deploy them as staticresources

**Comment by happiness801** [comment]
There are already other libraries that can make this happen pretty easily. I don't know if it belongs as part of the grunt-ant-sfdc plugin or not, though I can see a case for it.

We use the 'compress' plugin and have a task-list that looks something like this:

clean -> jshint -> copy -> less/compass -> compress -> rename -> write-meta -> antdeploy -> copy:localcopy -> clean

So, if the file is a folder, we copy the folder to a temporary directory and compress it to a zip file and rename it to .staticresource. We then copy the file to our local src/staticresources directory so that we can commit and deploy the compiled resource further up the chain.

It's really quite easy. If you want more specific details, I can help.

**Comment by andynormancx** [comment]
You don't even need a specific rename step, using the options in compress you can target the static resource directly.

`options: {
                        mode: 'zip',
                        archive: 'salesforce/src/staticresources/broadswordjs.resource'
                    }`

And with the `files` options in compress you can also carefully select the files you want, preserve directory structure where needed etc

**Comment by happiness801** [comment]
@andynormancx You're correct; great advice. I misread our gruntfile. We run compress if the target is a folder, and rename otherwise.

**Comment by kevinohara80** [comment]
Agree that this would be userland implementation and not something for this module. Thanks for the suggestion though!
